### ISSUE TITLE
Email and API key stored as Pulumi secrets are not recognised

### ISSUE THREAD

**Issue by 0xJem** [upstash/pulumi-upstash#11]
I stored the values as secrets (`pulumi config set --secret ...`) under `upstash:email` and `upstash:apiKey`, but when running a pulumi command, there is an error from the upstash plugin that it can't find the configuration values.

**Comment by burak-upstash** [comment]
Hey @0xJem, thanks for the issue.
I am unable to reproduce this. If I run the following commands:
```
pulumi config set --secret upstash:email <email>
pulumi config set --secret upstash:apiKey <apiKey>
```
It works for me.
Could it be the case you are using a different stack from the one you set those variables?

**Comment by 0xJem** [comment]
I added an explicit `--stack <STACK_NAME>` to the end of the `pulumi config get` command and the variables are set correctly.

Running `pulumi refresh`, I get:

```
  upstash:index:RedisDatabase (json-rpc-cache-autogen-integration-tests-arbitrum):
    	* missing required configuration key "upstash:email":
    Set a value using the command `pulumi config set upstash:email <value>`.
    	* missing required configuration key "upstash:apiKey":
    Set a value using the command `pulumi config set upstash:apiKey <value>`.
```

(the stack name is in the resource name, so I know that the pulumi stacks match up.)

Is there any step needed in the file importing "@upstash/pulumi" to tell it to use the Pulumi configuration file for authentication? e.g. grabbing the config through `new pulumi.Config("upstash")` and injecting a value from that into the `new upstash.RedisDatabase( ... )` call.

**Comment by praneetloke** [comment]
@0xJem it's possible that you only set those secrets for one of the stacks and the stack for which `pulumi refresh` is running is _not_ the stack that has those secrets. Try running `pulumi refresh --stack <stack name>` where `<stack name>` is the same stack for which you ran `pulumi config set --secret upstash:email --stack <stack name>`.

**Comment by 0xJem** [comment]
The values were set across all stacks and you can see in my comment above that running `pulumi refresh`, it used one of the stacks in which the values were set. After updating to 0.2.0, it seems to be working. *shrugs*
