### ISSUE TITLE
Support Upstash Vector

### ISSUE THREAD

**Issue by ian-pascoe** [upstash/pulumi-upstash#19]
Add support for Upstash Vector Index management

**Comment by fahreddinozcan** [comment]
Hey, it's currently in progress. I'll let you know when it's finalized

**Comment by fahreddinozcan** [comment]
Hey, vector support is added with #20. Therefore closing this.

**Comment by ian-pascoe** [comment]
@fahreddinozcan There was no new version pushed to npm. Therefore I cannot use this change still
