### ISSUE TITLE
v0.3.0 failed to build & is not published

### ISSUE THREAD

**Issue by klaemo** [upstash/pulumi-upstash#22]
Hey,
I'd like to use the new vector index feature that's supposed to be in version 0.3.0, but it seems like that version wasn't built and published correctly. The release of github doesn't include any pulumi artifacts.

Can you publish a fixed version, please?

**Comment by ian-pascoe** [comment]
@fahreddinozcan - This affects the release of #19 that I opened

**Comment by fahreddinozcan** [comment]
Sorry for the inconvenience here, working on the issue.

**Comment by fahreddinozcan** [comment]
Hey guys,

the release is now fixed.
