### ISSUE TITLE
Could not automatically download and install resource plugin 'pulumi-resource-upstash' at version v0.1.2

### ISSUE THREAD

**Issue by zhangpengchen** [upstash/pulumi-upstash#7]
Diagnostics:
  pulumi:providers:upstash (default_0_1_2_https_/github.com/upstash/pulumi-upstash/releases/download/v__VERSION_):
    error: Could not automatically download and install resource plugin 'pulumi-resource-upstash' at version v0.1.2, install the plugin using `pulumi plugin install resource upstash v0.1.2 --server https://github.com/upstash/pulumi-upstash/releases/download/v${VERSION}`: error downloading provider upstash to file: failed to download plugin: upstash-0.1.2: 404 HTTP error fetching plugin from https://github.com/upstash/pulumi-upstash/releases/download/v$%7BVERSION%7D/pulumi-resource-upstash-v0.1.2-darwin-amd64.tar.gz

**Comment by burak-upstash** [comment]
Hello, @zhangpengchen have you tried the command
```
pulumi plugin install resource upstash v0.1.2 --server https://github.com/upstash/pulumi-upstash/releases/download/v0.1.2
```
 It seems like you didn't change the version variable

**Comment by zhangpengchen** [comment]
@burak-upstash Thanks for the quick reply, the error message was triggered when I am running `pulumi up`.

If I ran `pulumi plugin install resource upstash v0.1.2 --server https://github.com/upstash/pulumi-upstash/releases/download/v0.1.2` then of course there is no issue.

**Comment by burak-upstash** [comment]
We have identified the issue, with the [PR](#10) waiting, we will both update the pulumi version and fix this automatically downloading issue.

**Comment by burak-upstash** [comment]
We have release v0.2.0, closing the issue for now.

**Comment by zhangpengchen** [comment]
Thanks @burak-upstash the new version works great
